name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site (optional if HTML already exists)
        run: mkdir output && cp -r * output/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
